pin "application"
pin "vault_crypto"
pin "credential_importer"
pin "argon2_bridge"
pin "openpgp", to: "openpgp.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
